export enum BookNames {
  GENESIS = "Genesis",
  EXODUS = "Exodus",
  LEVITICUS = "Leviticus",
  NUMBERS = "Numbers",
  DEUTERONOMY = "Deuteronomy",

  JOSHUA = "Joshua",
  JUDGES = "Judges",
  RUTH = "Ruth",
  SAMUEL1 = "1 Samuel",
  SAMUEL2 = "2 Samuel",
  KINGS1 = "1 Kings",
  KINGS2 = "2 Kings",
  CHRONICLES1 = "1 Chronicles",
  CHRONICLES2 = "2 Chronicles",
  EZRA = "Ezra",
  NEHEMIAH = "Nehemiah",
  ESTHER = "Esther",

  JOB = "Job",
  PSALMS = "Psalms",
  PROVERBS = "Proverbs",
  ECCLESIASTES = "Ecclesiastes",
  SONG_OF_SOLOMON = "Song of Solomon",

  ISAIAH = "Isaiah",
  JEREMIAH = "Jeremiah",
  LAMENTATIONS = "Lamentations",
  EZEKIEL = "Ezekiel",
  DANIEL = "Daniel",
  HOSEA = "Hosea",
  JOEL = "Joel",
  AMOS = "Amos",
  OBADIAH = "Obadiah",
  JONAH = "Jonah",
  MICAH = "Micah",
  NAHUM = "Nahum",
  HABAKKUK = "Habakkuk",
  ZEPHANIAH = "Zephaniah",
  HAGGAI = "Haggai",
  ZECHARIAH = "Zechariah",
  MALACHI = "Malachi",

  MATTHEW = "Matthew",
  MARK = "Mark",
  LUKE = "Luke",
  JOHN = "John",
  ACTS_OF_THE_APOSTLES = "Acts of the Apostles",

  JAMES = "James",
  PETER1 = "1 Peter",
  PETER2 = "2 Peter",
  JOHN1 = "1 John",
  JOHN2 = "2 John",
  JOHN3 = "3 John",
  JUDE = "Jude",

  ROMANS = "Romans",
  CORINTHIANS1 = "1 Corinthians",
  CORINTHIANS2 = "2 Corinthians",
  GALATIANS = "Galatians",
  EPHESIANS = "Ephesians",
  PHILIPPIANS = "Philippians",
  COLOSSIANS = "Colossians",
  THESSALONIANS1 = "1 Thessalonians",
  THESSALONIANS2 = "2 Thessalonians",
  TIMOTHY1 = "1 Timothy",
  TIMOTHY2 = "2 Timothy",
  TITUS = "Titus",
  PHILEMON = "Philemon",
  HEBREWS = "Hebrews",

  REVELATION = "Revelation",
}

export enum RussianBookNames {
  GENESIS = "Бытие",
  EXODUS = "Исход",
  LEVITICUS = "Левит",
  NUMBERS = "Числа",
  DEUTERONOMY = "Второзаконие",

  JOSHUA = "Иисуса Навина",
  JUDGES = "Судей Израилевых",
  RUTH = "Руфь",
  SAMUEL1 = "Царств (1)",
  SAMUEL2 = "Царств (2)",
  KINGS1 = "Царств (3)",
  KINGS2 = "Царств (4)",
  CHRONICLES1 = "Паралипоменон (1)",
  CHRONICLES2 = "Паралипоменон (2)",
  EZRA = "Ездры",
  NEHEMIAH = "Неемии",
  ESTHER = "Есфирь",

  JOB = "Иов",
  PSALMS = "Псалтирь",
  PROVERBS = "Притчей Соломоновых",
  ECCLESIASTES = "Екклезиаста",
  SONG_OF_SOLOMON = "Песни Песней Соломона",

  ISAIAH = "Исаия",
  JEREMIAH = "Иеремии",
  LAMENTATIONS = "Плач Иеремии",
  EZEKIEL = "Иезекииля",
  DANIEL = "Даниила",
  HOSEA = "Осии",
  JOEL = "Иoиля",
  AMOS = "Амоса",
  OBADIAH = "Авдия",
  JONAH = "Ионы",
  MICAH = "Михея",
  NAHUM = "Наума",
  HABAKKUK = "Аввакума",
  ZEPHANIAH = "Софонии",
  HAGGAI = "Аггея",
  ZECHARIAH = "Захарии",
  MALACHI = "Малахии",

  MATTHEW = "От Матфея",
  MARK = "От Марка",
  LUKE = "От Луки",
  JOHN = "От Иоанна",
  ACTS_OF_THE_APOSTLES = "Деяния святых Апостолов",

  JAMES = "Иакова",
  PETER1 = "Петра (1)",
  PETER2 = "Петра (2)",
  JOHN1 = "Иоанна (1)",
  JOHN2 = "Иоанна (2)",
  JOHN3 = "Иоанна (3)",
  JUDE = "Иуды",

  ROMANS = "К римлянам",
  CORINTHIANS1 = "К коринфянам (1)",
  CORINTHIANS2 = "К коринфянам (2)",
  GALATIANS = "К галатам",
  EPHESIANS = "К ефесянам",
  PHILIPPIANS = "К филиппийцам",
  COLOSSIANS = "К колоссянам",
  THESSALONIANS1 = "К фессалоникийцам (1)",
  THESSALONIANS2 = "К фессалоникийцам (2)",
  TIMOTHY1 = "К Тимофею (1)",
  TIMOTHY2 = "К Тимофею (2)",
  TITUS = "К Титу",
  PHILEMON = "К Филимону",
  HEBREWS = "К евреям",

  REVELATION = "Откровение Иоанна Богослова (Апокалипсис)",
}
